### ISSUE TITLE
Error code -8 when reading 1200000 bytes

### ISSUE THREAD

**Issue by FFY00** [randaller/cnn-rtlsdr#4]
I'm getting this when trying to run `predict_scan.py`.

```
Traceback (most recent call last):
  File "predict_scan.py", line 54, in <module>
    iq_samples = read_samples(sdr, freq)
  File "predict_scan.py", line 13, in read_samples
    return sdr.read_samples(sample_rate * 0.25)
  File "/home/anubis/anaconda3/lib/python3.6/site-packages/rtlsdr/rtlsdr.py", line 407, in read_samples
    raw_data = self.read_bytes(num_bytes)
  File "/home/anubis/anaconda3/lib/python3.6/site-packages/rtlsdr/rtlsdr.py", line 391, in read_bytes
    % (result, num_bytes))
OSError: Error code -8 when reading 1200000 bytes
```

**Comment by randaller** [comment]
This happens under Linux and solved here: https://github.com/randaller/cnn-rtlsdr/issues/1#issuecomment-362221873

**Comment by randaller** [comment]
Fixed and committed
