### ISSUE TITLE
running train.py

### ISSUE THREAD

**Issue by MajeedSan** [randaller/cnn-rtlsdr#5]
I'm facing this error when I try to run 'train.py' with your default train data. (also i didn't change anything in code) 
Do you have any idea how for solving this?

```
Traceback (most recent call last):
  File "blablabla/cnn-rtlsdr-master/train.py", line 145, in <module>
    x_batch, y_true_batch, _, cls_batch = data.train.next_batch(batch_size)
  File "blablabla\cnn-rtlsdr-master\dataset2.py", line 191, in next_batch
    assert batch_size <= self._num_examples
AssertionError
```

**Comment by swiich** [comment]
> I'm facing this error when I try to run 'train.py' with your default train data. (also i didn't change anything in code)
> Do you have any idea how for solving this?
> 
> ```
> Traceback (most recent call last):
>   File "blablabla/cnn-rtlsdr-master/train.py", line 145, in <module>
>     x_batch, y_true_batch, _, cls_batch = data.train.next_batch(batch_size)
>   File "blablabla\cnn-rtlsdr-master\dataset2.py", line 191, in next_batch
>     assert batch_size <= self._num_examples
> AssertionError
> ```
> (This error doesn't occur when i use 'train_keras.py'.)
batch_size should be 1 with default train data

**Comment by swiich** [comment]
> I'm facing this error when I try to run 'train.py' with your default train data. (also i didn't change anything in code)
> Do you have any idea how for solving this?
> 
> ```
> Traceback (most recent call last):
>   File "blablabla/cnn-rtlsdr-master/train.py", line 145, in <module>
>     x_batch, y_true_batch, _, cls_batch = data.train.next_batch(batch_size)
>   File "blablabla\cnn-rtlsdr-master\dataset2.py", line 191, in next_batch
>     assert batch_size <= self._num_examples
> AssertionError
> ```
> (This error doesn't occur when i use 'train_keras.py'.)


the batch_size should be 1 with default train data

**Comment by saaws2** [comment]
Want to ask sorry for post jacking but I don't know any thing about GitHub . The question is. Would 2 AMD RX480 8gb cards allow me to do any thing with this software? It's just the thing I wanted to look into. Again sorry if am in violation of rules .

**Comment by randaller** [comment]
You may do everything even without GPU card, using only CPU for neural network.
